"""redd — module shim so `python -m redd` works.

`redd` is a console script, generated by pip from
`[project.scripts] redd = "signal_audit_cli:main"`. That produces
`redd.exe` (or `redd`) in the interpreter's Scripts/bin directory, and
on Windows that directory is frequently NOT on PATH — pip says so in a
warning that scrolls past during install:

    WARNING: The script redd.exe is installed in '...\\Scripts'
    which is not on PATH.

The obvious recovery is `python -m redd`, which then fails with "No
module named redd", because a console script is not a module. That is
two confusing errors in a row for someone who installed the package
correctly, so this file exists to make the obvious thing work.

`python -m signal_audit_cli` also works and always did; this is the
spelling people actually reach for.
"""

from signal_audit_cli import main

if __name__ == "__main__":
    raise SystemExit(main())
